### PR TITLE
Release `1.5.0`

### PR DESCRIPTION
**Pull request by robbot006**
This is a draft of changelog for the `1.5.0` release.
Here you can find all related translations changes: [1.4.0...main](https://github.com/flarum-lang/spanish/compare/1.4.0...main).

> ### ⚠️ Do not merge this pull request manually ⚠️
> 
> You should **[approve](https://github.com/rob006-software/flarum-translations/wiki/How-to-approve-release-pull-request)** this pull request instead. After approving, I will automatically update it (release date needs to be adjusted), merge, and tag a new release. You can read more about the process on [forum](https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate/76).

<details>
<summary>Show release notes preview</summary>

## 1.5.0

**General changes**:

* Updated Flarum core translations.

**Added support for new extensions**:

* [`clarkwinkelmann/flarum-ext-post-stream-search`](https://github.com/clarkwinkelmann/flarum-ext-post-stream-search)
* [`fof/disposable-emails`](https://github.com/FriendsOfFlarum/disposable-emails)
* [`kilowhat/flarum-ext-audit-free`](https://github.com/kilowhat/flarum-ext-audit-free)
* [`michaelbelgium/flarum-discussion-views`](https://github.com/MichaelBelgium/flarum-discussion-views)

**Updated translations for extensions**:

* [`clarkwinkelmann/flarum-ext-author-change`](https://github.com/clarkwinkelmann/flarum-ext-author-change)
* [`clarkwinkelmann/flarum-ext-first-post-approval`](https://github.com/clarkwinkelmann/flarum-ext-first-post-approval)
* [`flarum/likes`](https://github.com/flarum/likes)
* [`flarum/markdown`](https://github.com/flarum/markdown)
* [`flarum/mentions`](https://github.com/flarum/mentions)
* [`flarum/suspend`](https://github.com/flarum/suspend)
* [`flarum/tags`](https://github.com/flarum/tags)
* [`fof/forum-statistics-widget`](https://github.com/FriendsOfFlarum/forum-statistics-widget)
* [`fof/links`](https://github.com/FriendsOfFlarum/links)
* [`fof/masquerade`](https://github.com/FriendsOfFlarum/masquerade)
* [`fof/oauth`](https://github.com/FriendsOfFlarum/oauth)
* [`fof/polls`](https://github.com/FriendsOfFlarum/polls)
* [`fof/share-social`](https://github.com/FriendsOfFlarum/share-social)
* [`fof/socialprofile`](https://github.com/FriendsOfFlarum/socialprofile)
* [`fof/user-directory`](https://github.com/FriendsOfFlarum/user-directory)
* [`sycho/flarum-move-posts`](https://github.com/SychO9/flarum-move-posts)

All changes: [1.4.0...1.5.0](https://github.com/flarum-lang/spanish/compare/1.4.0...1.5.0).

</details>

### CODE REVIEW

**Comment by jslirola** [comment]
@iamdarkle hay una cadena que he puesto y no me termina de convencer, quizás porque estoy acostumbrado a verlo en inglés.

```
likes_link: 'Me gustas'
```

Si no me equivoco es lo que se muestra en el menú del perfil de usuario para ver todos los _likes_. ¿Te parece bien o restablecemos a _Likes_?

**Comment by iamdarkle** [comment]
Ya, estando acostumbrado se hace un poco raro, pero yo sinceramente lo veo bien, como dentro los posts usamos "Me gusta/ Ya no me gusta" creo que así queda más acorde con el resto.

**Comment by jslirola** [comment]
Perfecto, lo dejamos y mantenemos la coherencia. Acabo de traducir la extensión `markdown` que teníamos pendiente como te comenté en el foro.

En caso de cuadrarte estos y el resto de traducciones podemos mezclar este PR, que ya se han acumulado unas cuantas extensiones.

Un saludo.

**Comment by iamdarkle** [comment]
Genial, muchas gracias! Un saludo.

**Review by iamdarkle — APPROVED** [review]

**Comment by robbot006** [comment]
Success! Now you can announce new release on [forum](https://discuss.flarum.org/t/languages):

~~~markdown
## Version [`1.5.0`](https://github.com/flarum-lang/spanish/releases/tag/1.5.0)

**General changes**:

* Updated Flarum core translations.


**Added support for new extensions**:

* [`clarkwinkelmann/flarum-ext-post-stream-search`](https://github.com/clarkwinkelmann/flarum-ext-post-stream-search)
* [`fof/disposable-emails`](https://github.com/FriendsOfFlarum/disposable-emails)
* [`kilowhat/flarum-ext-audit-free`](https://github.com/kilowhat/flarum-ext-audit-free)
* [`michaelbelgium/flarum-discussion-views`](https://github.com/MichaelBelgium/flarum-discussion-views)


**Updated translations for extensions**:

* [`clarkwinkelmann/flarum-ext-author-change`](https://github.com/clarkwinkelmann/flarum-ext-author-change)
* [`clarkwinkelmann/flarum-ext-first-post-approval`](https://github.com/clarkwinkelmann/flarum-ext-first-post-approval)
* [`flarum/likes`](https://github.com/flarum/likes)
* [`flarum/markdown`](https://github.com/flarum/markdown)
* [`flarum/mentions`](https://github.com/flarum/mentions)
* [`flarum/suspend`](https://github.com/flarum/suspend)
* [`flarum/tags`](https://github.com/flarum/tags)
* [`fof/forum-statistics-widget`](https://github.com/FriendsOfFlarum/forum-statistics-widget)
* [`fof/links`](https://github.com/FriendsOfFlarum/links)
* [`fof/masquerade`](https://github.com/FriendsOfFlarum/masquerade)
* [`fof/oauth`](https://github.com/FriendsOfFlarum/oauth)
* [`fof/polls`](https://github.com/FriendsOfFlarum/polls)
* [`fof/share-social`](https://github.com/FriendsOfFlarum/share-social)
* [`fof/socialprofile`](https://github.com/FriendsOfFlarum/socialprofile)
* [`fof/user-directory`](https://github.com/FriendsOfFlarum/user-directory)
* [`sycho/flarum-move-posts`](https://github.com/SychO9/flarum-move-posts)


All changes: [1.4.0...1.5.0](https://github.com/flarum-lang/spanish/compare/1.4.0...1.5.0).

In order to update run these commands:

```console
composer update flarum-lang/spanish
php flarum cache:clear
```

~~~

**Pull request merged**
