### PR TITLE
Release `1.4.0`

### PR DESCRIPTION
**Pull request by robbot006**
This is a draft of changelog for the `1.4.0` release.
Here you can find all related translations changes: [1.3.2...main](https://github.com/flarum-lang/spanish/compare/1.3.2...main).

> ### ⚠️ Do not merge this pull request manually ⚠️
> 
> You should **[approve](https://github.com/rob006-software/flarum-translations/wiki/How-to-approve-release-pull-request)** this pull request instead. After approving, I will automatically update it (release date needs to be adjusted), merge, and tag a new release. You can read more about the process on [forum](https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate/76).

<details>
<summary>Show release notes preview</summary>

## 1.4.0

**General changes**:

* Updated Flarum core translations.

**Added support for new extensions**:

* [`clarkwinkelmann/flarum-ext-author-change`](https://github.com/clarkwinkelmann/flarum-ext-author-change)
* [`fof/follow-tags`](https://github.com/FriendsOfFlarum/follow-tags)
* [`fof/webhooks`](https://github.com/FriendsOfFlarum/webhooks)
* [`sycho/flarum-move-posts`](https://github.com/SychO9/flarum-move-posts)

**Updated translations for extensions**:

* [`flarum/likes`](https://github.com/flarum/likes)
* [`flarum/mentions`](https://github.com/flarum/mentions)
* [`flarum/statistics`](https://github.com/flarum/statistics)
* [`justoverclock/related-discussions`](https://extiverse.com/extension/justoverclock/related-discussions)

All changes: [1.3.2...1.4.0](https://github.com/flarum-lang/spanish/compare/1.3.2...1.4.0).

</details>

### CODE REVIEW

**Comment by jslirola** [comment]
Buenas @iamdarkle 

He traducido un par de extensiones y completado alguna cadena de otras extensiones para ir cubriendo lo más visible de las últimas versiones de Flarum. Me queda una duda en dos cadenas de texto de la extensión de estadísticas, echa un vistazo y me dices qué deberíamos poner en base al contexto:
- https://weblate.rob006.net/translate/flarum/flarum-statistics/es/?checksum=ebfcb400c01f11ee&sort_by=-priority,position
- https://weblate.rob006.net/translate/flarum/flarum-statistics/es/?checksum=da84c8b33a3952fa&sort_by=-priority,position

imagen

Una vez completadas esas podemos aprobar el PR para ser mezclado.

**Comment by iamdarkle** [comment]
Buenas, al verlo así de primeras también he dudado, pero teniendo en cuenta el contexto creo que 'Últimos' y 'Anteriores' se deberían diferenciar lo suficientemente bien no?

**Comment by jslirola** [comment]
Creo que sí pero prefería confirmarlo contigo por si no estaba claro. Ya los he añadido, si te parecen bien las traducciones hechas puedes aprobarlo ya:

https://github.com/flarum-lang/spanish/compare/1.3.2...main

Un saludo.

**Review by iamdarkle — APPROVED** [review]

**Comment by robbot006** [comment]
Success! Now you can announce new release on [forum](https://discuss.flarum.org/t/languages):

~~~markdown
## Version [`1.4.0`](https://github.com/flarum-lang/spanish/releases/tag/1.4.0)

**General changes**:

* Updated Flarum core translations.


**Added support for new extensions**:

* [`clarkwinkelmann/flarum-ext-author-change`](https://github.com/clarkwinkelmann/flarum-ext-author-change)
* [`fof/follow-tags`](https://github.com/FriendsOfFlarum/follow-tags)
* [`fof/webhooks`](https://github.com/FriendsOfFlarum/webhooks)
* [`sycho/flarum-move-posts`](https://github.com/SychO9/flarum-move-posts)


**Updated translations for extensions**:

* [`flarum/likes`](https://github.com/flarum/likes)
* [`flarum/mentions`](https://github.com/flarum/mentions)
* [`flarum/statistics`](https://github.com/flarum/statistics)
* [`justoverclock/related-discussions`](https://extiverse.com/extension/justoverclock/related-discussions)


All changes: [1.3.2...1.4.0](https://github.com/flarum-lang/spanish/compare/1.3.2...1.4.0).

In order to update run these commands:

```console
composer update flarum-lang/spanish
php flarum cache:clear
```

~~~

**Pull request merged**
