### PR TITLE
Release `1.9.0`

### PR DESCRIPTION
**Pull request by robbot006**
This is a draft of changelog for the `1.9.0` release.
Here you can find all related translations changes: [1.8.0...main](https://github.com/flarum-lang/spanish/compare/1.8.0...main).

> ### ⚠️ Do not merge this pull request manually ⚠️
> 
> You should **[approve](https://github.com/rob006-software/flarum-translations/wiki/How-to-approve-release-pull-request)** this pull request instead. After approving, I will automatically update it (release date needs to be adjusted), merge, and tag a new release. You can read more about the process on [forum](https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate/76).

<details>
<summary>Show release notes preview</summary>

## 1.9.0

**General changes**:

* Updated validation translations.

**Added support for new extensions**:

* [`akr/chevereto`](https://github.com/AKR-Developers/flarum-chevereto)
* [`flarum/extension-manager`](https://github.com/flarum/extension-manager)

**Updated translations for extensions**:

* [`flarum/tags`](https://github.com/flarum/tags)

All changes: [1.8.0...1.9.0](https://github.com/flarum-lang/spanish/compare/1.8.0...1.9.0).

</details>

### CODE REVIEW

**Comment by jslirola** [comment]
Lo veo bien, un detalle que cambiaría en la versión informal es esta cadena:

https://github.com/flarum-lang/spanish/compare/1.8.0...main#diff-4cc177692ecae644cd9f73fdaa2b13fc032ba4ef174adf04f16c504175b30ff7R16

Que sea referido a "tú" en lugar de "usted". Pero es algo que podemos aprobar si andamos los dos tan mal de disponibilidad como yo.

Saludos.

**Comment by iamdarkle** [comment]
Vaya, no vi la notificación. Por casualidad revisé el repositorio y lo he visto ahora. @jslirola , he actualizado lo que comentabas y he completado el resto de las cadenas que faltaban del Extension Manager. Si te parecen bien los cambios, lanzamos la nueva versión.

Un saludo 👋

**Comment by jslirola** [comment]
Perfecto @iamdarkle 

Lo acabo de revisar y veo que se han mantenido la forma de "usted" en ambas traducciones. No lo veo un gran problema, si puedes cambiarlo en la versión formal, estupendo, sino adelante con la versión:

https://github.com/flarum-lang/spanish/compare/main%40%7B1day%7D...main#diff-6b0f6f4b475a3dd5c5fe62706ab8cd33e30c678e516bd04804010b28b8dfa7d1L16

https://github.com/flarum-lang/spanish/compare/main%40%7B1day%7D...main#diff-6b0f6f4b475a3dd5c5fe62706ab8cd33e30c678e516bd04804010b28b8dfa7d1R32

https://github.com/flarum-lang/spanish/compare/main%40%7B1day%7D...main#diff-6b0f6f4b475a3dd5c5fe62706ab8cd33e30c678e516bd04804010b28b8dfa7d1R50

https://github.com/flarum-lang/spanish/compare/main%40%7B1day%7D...main#diff-6b0f6f4b475a3dd5c5fe62706ab8cd33e30c678e516bd04804010b28b8dfa7d1R69

https://github.com/flarum-lang/spanish/compare/main%40%7B1day%7D...main#diff-6b0f6f4b475a3dd5c5fe62706ab8cd33e30c678e516bd04804010b28b8dfa7d1R125

https://github.com/flarum-lang/spanish/compare/main%40%7B1day%7D...main#diff-6b0f6f4b475a3dd5c5fe62706ab8cd33e30c678e516bd04804010b28b8dfa7d1R126

https://github.com/flarum-lang/spanish/compare/main%40%7B1day%7D...main#diff-6b0f6f4b475a3dd5c5fe62706ab8cd33e30c678e516bd04804010b28b8dfa7d1R128

Un saludo.

**Comment by iamdarkle** [comment]
No estoy seguro de que paso, lo hice con la carga de archivo, y tal vez no se sustituyeron (?), creo que ahora ya se reflejan los cambios.

**Comment by jslirola** [comment]
Estupendo, ahora sí. Puedes desplegar cuando quieras. :)

**Review by iamdarkle — APPROVED** [review]

**Comment by robbot006** [comment]
Success! Now you can announce new release on [forum](https://discuss.flarum.org/t/languages):

~~~markdown
## Version [`1.9.0`](https://github.com/flarum-lang/spanish/releases/tag/1.9.0)

**General changes**:

* Updated validation translations.


**Added support for new extensions**:

* [`akr/chevereto`](https://github.com/AKR-Developers/flarum-chevereto)
* [`flarum/extension-manager`](https://github.com/flarum/extension-manager)


**Updated translations for extensions**:

* [`flarum/tags`](https://github.com/flarum/tags)


All changes: [1.8.0...1.9.0](https://github.com/flarum-lang/spanish/compare/1.8.0...1.9.0).

In order to update run these commands:

```console
composer update flarum-lang/spanish
php flarum cache:clear
```

~~~

**Pull request merged**
